from __future__ import annotations

from typing import TYPE_CHECKING, Any, Protocol, TypeVar

if TYPE_CHECKING:
    from narwhals._plan.logical_plan import plan as lp
    from narwhals._plan.logical_plan.resolved import ResolvedPlan


R_co = TypeVar("R_co", covariant=True)


class LogicalVisitor(Protocol[R_co]):
    """Generic `LogicalPlan` visitor protocol.

    Defines the method name of each node.
    """

    def collect(self, plan: lp.Collect, /) -> R_co: ...
    def concat_horizontal(self, plan: lp.HConcat, /) -> R_co: ...
    def concat_vertical(self, plan: lp.VConcat, /) -> R_co: ...
    def explode(self, plan: lp.MapFunction[lp.Explode], /) -> R_co: ...
    def filter(self, plan: lp.Filter, /) -> R_co: ...
    def group_by(self, plan: lp.GroupBy, /) -> R_co: ...
    def join(self, plan: lp.Join, /) -> R_co: ...
    def join_asof(self, plan: lp.JoinAsof, /) -> R_co: ...
    def map_function(self, plan: lp.MapFunction[lp.LpFunctionT_co], /) -> R_co: ...
    def pivot(self, plan: lp.Pivot, /) -> R_co: ...
    def rename(self, plan: lp.MapFunction[lp.Rename], /) -> R_co: ...
    def scan_csv(self, plan: lp.ScanCsv, /) -> R_co: ...
    def scan_dataframe(self, plan: lp.ScanDataFrame, /) -> R_co: ...
    def scan_parquet(self, plan: lp.ScanParquet, /) -> R_co: ...
    def scan_parquet_impl(self, plan: lp.ScanParquetImpl[Any], /) -> R_co: ...
    def select(self, plan: lp.Select, /) -> R_co: ...
    def select_names(self, plan: lp.SelectNames, /) -> R_co: ...
    def sink_parquet(self, plan: lp.SinkParquet, /) -> R_co: ...
    def slice(self, plan: lp.Slice, /) -> R_co: ...
    def sort(self, plan: lp.Sort, /) -> R_co: ...
    def unique(self, plan: lp.Unique, /) -> R_co: ...
    def unique_by(self, plan: lp.UniqueBy, /) -> R_co: ...
    def unnest(self, plan: lp.MapFunction[lp.Unnest], /) -> R_co: ...
    def unpivot(self, plan: lp.MapFunction[lp.Unpivot], /) -> R_co: ...
    def with_columns(self, plan: lp.WithColumns, /) -> R_co: ...
    def with_row_index(self, plan: lp.MapFunction[lp.RowIndex], /) -> R_co: ...
    def with_row_index_by(self, plan: lp.MapFunction[lp.RowIndexBy], /) -> R_co: ...


class LogicalToResolved(LogicalVisitor["ResolvedPlan"], Protocol):
    """`LogicalPlan` -> `ResolvedPlan` visitor."""

    def map_function(self, plan: lp.MapFunction[lp.LpFunctionT_co], /) -> ResolvedPlan:
        return plan.function.resolve(self, plan)
