name-template: 'Narwhals unreleased'
version-template: unreleased

change-template: '- $TITLE (#$NUMBER)'

categories:
  - type: "pre-exclude"
    when:
      labels:
        - ignore
        - release
        - dependencies
  - title: 🏆 Highlights
    when:
      label: highlight
  - title: 💥 Breaking changes
    when:
      label: breaking
  - title: ⚠️ Deprecations
    when:
      label: deprecation
  - title: 🚀 Performance improvements
    when:
      label: performance
  - title: ✨ Enhancements
    when:
      label: enhancement
  - title: 🐞 Bug fixes
    when:
      label: fix
  - title: 📖 Documentation
    when:
      label: documentation
  - title: 📦 Build system
    when:
      label: build
  - title: 🛠️ Other improvements
    when:
      label: internal

template: |
  ## Changes

  $CHANGES

  Thank you to all our contributors for making this release possible!
  $CONTRIBUTORS
