[default.extend-words]
ser = "ser"  # Used in Series classes
ND = "ND"  # Used in NativeNDFrameT
ba = "ba"  # Used as column name in docstring examples (way too much?)
iy = "iy"  # Used as column name (once in a test)
pn = "pn"  # Used in docs: pn = PandasLikeNamespace(...)
TYP = "TYP"  # Used in flake8 rule

[files]
extend-exclude = ["tests/data/*"]
