[project]
site_name = "Narwhals"
site_description = "Narwhals documentation"
site_url = "https://narwhals-dev.github.io/narwhals/"
site_author = "hello_narwhals@proton.me"
repo_url = "https://github.com/narwhals-dev/narwhals"
repo_name = "narwhals-dev/narwhals"

nav = [
    { "Home" = "index.md" },
    { "Why" = "why.md" },
    { "Installation and quick start" = "installation.md"},
    { "Intro tutorial" = [
        "basics/dataframe.md",
        "basics/series.md",
        "basics/complete_example.md",
        "basics/dataframe_conversion.md",
        ]},
    {"Narwhals and SQL" = "generating_sql.md"},
    { "Concepts" = [
        "concepts/order_dependence.md",
        "concepts/pandas_index.md",
        "concepts/improve_group_by_operation.md",
        "concepts/column_names.md",
        "concepts/boolean.md",
        "concepts/null_handling.md",
    ]},
    {"Overhead" = "overhead.md"},
    {"Perfect backwards compatibility policy" = "backcompat.md"},
    {"Extensions and Plugins" = "extending.md"},
    {"How it works" = "how_it_works.md"},
    {"Ecosystem" = "ecosystem.md"},
    {"Security" = "security.md"},
    {"Resources" = "resources.md"},
    {"API Completeness" = [
        {"API Completeness" = "api-completeness/index.md"},
        {"Supported Top-level functions" = "api-completeness/functions.md"},
        {"Supported DataFrame methods" = "api-completeness/dataframe.md"},
        {"Supported LazyFrame methods" = "api-completeness/lazyframe.md"},
        {"Supported Expr methods" = "api-completeness/expr.md"},
        {"Supported Expr.cat methods" = "api-completeness/expr_cat.md"},
        {"Supported Expr.dt methods" = "api-completeness/expr_dt.md"},
        {"Supported Expr.list methods" = "api-completeness/expr_list.md"},
        {"Supported Expr.name methods" = "api-completeness/expr_name.md"},
        {"Supported Expr.str methods" = "api-completeness/expr_str.md"},
        {"Supported Expr.struct methods" = "api-completeness/expr_struct.md"},
        {"Supported Series methods" = "api-completeness/series.md"},
        {"Supported Series.cat methods" = "api-completeness/series_cat.md"},
        {"Supported Series.dt methods" = "api-completeness/series_dt.md"},
        {"Supported Series.list methods" = "api-completeness/series_list.md"},
        {"Supported Series.str methods" = "api-completeness/series_str.md"},
        {"Supported Series.struct methods" = "api-completeness/series_struct.md"},
    ]},
    {"API Reference" = [
        "api-reference/index.md",
        "api-reference/narwhals.md",
        "api-reference/dataframe.md",
        "api-reference/expr.md",
        "api-reference/expr_cat.md",
        "api-reference/expr_dt.md",
        "api-reference/expr_list.md",
        "api-reference/expr_name.md",
        "api-reference/expr_str.md",
        "api-reference/expr_struct.md",
        "api-reference/group_by.md",
        "api-reference/lazy_group_by.md",
        "api-reference/lazyframe.md",
        "api-reference/schema.md",
        "api-reference/series.md",
        "api-reference/series_cat.md",
        "api-reference/series_dt.md",
        "api-reference/series_list.md",
        "api-reference/series_str.md",
        "api-reference/series_struct.md",
        "api-reference/dependencies.md",
        "api-reference/implementation.md",
        "api-reference/dtypes.md",
        "api-reference/exceptions.md",
        "api-reference/selectors.md",
        "api-reference/sql.md",
        "api-reference/testing.md",
        "api-reference/typing.md",
        "api-reference/utils.md",
    ]},
    { "API Reference (Experimental)" = [
        "api-reference-plan/index.md", 
        "api-reference-plan/functions.md",
        "api-reference-plan/dataframe.md",
        "api-reference-plan/lazyframe.md",
        { "Expressions" = [
            "api-reference-plan/expr/index.md",
            "api-reference-plan/expr/categorical.md",
            "api-reference-plan/expr/list.md",
            "api-reference-plan/expr/meta.md",
            "api-reference-plan/expr/name.md",
            "api-reference-plan/expr/string.md",
            "api-reference-plan/expr/struct.md",
            "api-reference-plan/expr/temporal.md",
        ]},
        "api-reference-plan/selectors.md", 
        "api-reference-plan/series.md", 
        { "IR" = [
            "api-reference-plan/ir/index.md",
            { "ExprIR" = [
                "api-reference-plan/ir/expr-ir/index.md",
                "api-reference-plan/ir/expr-ir/agg_expr.md",
                "api-reference-plan/ir/expr-ir/function_expr.md",
                "api-reference-plan/ir/expr-ir/function.md",
                "api-reference-plan/ir/expr-ir/selectors.md",
            ]},
            "api-reference-plan/ir/named-ir.md",
        ]},
        "api-reference-plan/typing.md",
    ] },
    {"This" = "this.md"}
]

extra_css = [
    "css/extra.css",
    "https://unpkg.com/katex@0/dist/katex.min.css",
]
extra_javascript = [
    "javascripts/katex.js",
    "javascripts/extra.js",
    "javascripts/table.js",
    "https://unpkg.com/katex@0/dist/katex.min.js",
    "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js",
    "https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js",
]

[project.theme]
variant = "modern"  # "classic"
favicon = "assets/logo.svg"
logo = "assets/logo.svg"
language = "en"
features = [
    "content.code.annotate",
    "content.code.copy",
    "navigation.footer",
    "navigation.indexes",
    "navigation.top",
    "search.highlight",
    "toc.follow",
    # NOTE: Fixes a bug where a `<span ...>` got injected into the `title` string?
    # Also looks nice
    "content.tooltips"
]

[project.theme.font]
text = "Inter"
code = "Jetbrains Mono"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/narwhals-dev/narwhals"

[project.plugins.mkdocstrings.handlers.python]
# https://mkdocstrings.github.io/usage/#cross-references-to-other-projects-inventories
inventories = [
    "https://docs.python.org/3/objects.inv", 
    "https://docs.pola.rs/py-polars/html/objects.inv",  # https://github.com/pola-rs/polars/issues/7027
    "https://pandas.pydata.org/docs/objects.inv",
    "https://arrow.apache.org/docs/objects.inv",
    "https://numpy.org/doc/stable/objects.inv",
    "https://typing-extensions.readthedocs.io/en/latest/objects.inv",
    # https://github.com/ibis-project/ibis/issues/11723
    # TODO @dangotbanned: cudf, dask, duckdb, pyspark, sqlframe
]
paths = ["narwhals"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
members_order = "alphabetical"
separate_signature = true
show_signature_annotations = true
show_source = false
show_if_no_docstring = true  # remember to turn this off after listing members everywhere
signature_crossrefs = true
type_parameter_headings = true
line_length = 90  # (default: 60) this matches our ruff config
filters = [
    "!^_",
    "^__",
    # above are default filters, everything after refines from them
    # https://mkdocstrings.github.io/python/usage/configuration/members/#filters
    "!^_+(repr|slots|all)"
]


[project.markdown_extensions.admonition]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "python", class = "python", format = "markdown_exec.formatter", validator = "markdown_exec.validator"}
]

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji" 
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.pymdownx.tilde]
[project.markdown_extensions.pymdownx.highlight]
# https://mkdocstrings.github.io/recipes/#automatic-highlighting-for-indented-code-blocks-in-docstrings
pygments_lang_class = true
default_lang = "python"