#!/usr/bin/env python
"""Run narwhals' own test suite against `narwhals-dict`.

Mirrors the approach of `narwhals-daft`: narwhals' `tests/conftest.py` skips its
own constructor parametrization when `--use-external-constructor` is passed, and
the `narwhals_dict.testing` pytest plugin injects a plain-dict constructor
instead. Tests that are known to fail (mostly `not_implemented` functionality)
are excluded via `-k`.

Usage, from anywhere inside the repository:

    python packages/narwhals-dict/run_tests.py             # excludes known failures
    python packages/narwhals-dict/run_tests.py --update    # regenerate TESTS_THAT_NEED_FIX
    python packages/narwhals-dict/run_tests.py -x -q ...   # extra args pass through to pytest

Fixing a `not_implemented` method? Run with `--update` afterwards to shrink the list.
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parent
REPO_ROOT = PACKAGE_ROOT.parents[1]

# fmt: off
# --- BEGIN TESTS_THAT_NEED_FIX (auto-generated, see --update) ---
TESTS_THAT_NEED_FIX: list[str] = [
    "test_2d_array",
    "test_actual_object",
    "test_aggregation_over_without_partition_by",
    "test_anti_join",
    "test_any_value_over",
    "test_array_dunder",
    "test_array_dunder_with_copy",
    "test_array_dunder_with_dtype",
    "test_by_slice",
    "test_cast",
    "test_cast_decimal_to_native",
    "test_cast_series",
    "test_cast_struct",
    "test_cast_to_enum_v1",
    "test_cast_to_enum_vmain",
    "test_cast_to_float16",
    "test_categorical",
    "test_categorical_as_str",
    "test_check_order",
    "test_check_row_order",
    "test_check_schema_mismatch",
    "test_collect_to_default_backend",
    "test_collect_to_valid_backend_pandas",
    "test_collect_to_valid_backend_pandas_mod",
    "test_collect_to_valid_backend_polars",
    "test_collect_to_valid_backend_polars_mod",
    "test_collect_to_valid_backend_pyarrow",
    "test_collect_to_valid_backend_pyarrow_mod",
    "test_concat_horizontal_mismatched",
    "test_contains_expr",
    "test_contains_series",
    "test_convert",
    "test_convert_pandas",
    "test_convert_polars",
    "test_corr_expr",
    "test_corr_pairwise_nulls",
    "test_corr_series",
    "test_cov_expr",
    "test_cov_expr_inputs",
    "test_cov_invalid_denominator",
    "test_cov_series",
    "test_cov_single_valid_pair_population",
    "test_cross_join",
    "test_cross_join_suffix",
    "test_datetime",
    "test_diff_lazy",
    "test_diff_lazy_grouped",
    "test_duration_attributes_nano",
    "test_duration_attributes_series_nano",
    "test_enum_distinct_from_categorical",
    "test_estimated_size",
    "test_ew_mean",
    "test_ewm_mean_expr",
    "test_ewm_mean_expr_adjust",
    "test_ewm_mean_nulls",
    "test_ewm_mean_params",
    "test_ewm_mean_series",
    "test_explode_invalid_operation_error",
    "test_explode_multiple_cols",
    "test_explode_shape_error",
    "test_explode_single_col",
    "test_expr_floordiv_by_zero",
    "test_expr_rfloordiv_by_zero",
    "test_expr_rtruediv_by_zero",
    "test_expr_sample",
    "test_expr_sample_fraction",
    "test_expr_truediv_by_zero",
    "test_fill_nan",
    "test_fill_nan_series",
    "test_fill_null_expr_limits",
    "test_fill_null_limits",
    "test_fill_null_series_limit_as_none",
    "test_fill_null_series_limits",
    "test_fill_null_strategies_with_limit_as_none",
    "test_fill_null_strategies_with_partition_by",
    "test_filter_windows_over",
    "test_filter_with_boolean_list_predicates_eager",
    "test_filter_with_predicates_and_constraints",
    "test_first_expr_over_order_by_partition_by",
    "test_first_last_different_orders",
    "test_first_last_expr_over_order_by",
    "test_from_dict_one_native_one_narwhals",
    "test_from_dict_without_backend",
    "test_from_numpy",
    "test_from_numpy_schema_dict",
    "test_from_numpy_schema_list",
    "test_from_numpy_square",
    "test_from_numpy_square_roundtrip",
    "test_full_join",
    "test_full_join_duplicate",
    "test_full_join_with_overlapping_non_key_columns_and_nulls",
    "test_get_categories_eager",
    "test_get_categories_lazy",
    "test_get_expr",
    "test_get_field_expr",
    "test_get_field_series",
    "test_get_series",
    "test_group_by_window",
    "test_inner_join_single_key",
    "test_inner_join_two_keys",
    "test_is_close_expr_with_expr",
    "test_is_close_expr_with_scalar",
    "test_is_close_series_with_scalar",
    "test_is_close_series_with_series",
    "test_is_duplicated",
    "test_is_duplicated_with_nulls",
    "test_is_finite_expr",
    "test_is_finite_series",
    "test_is_first_distinct_expr_lazy",
    "test_is_first_distinct_expr_lazy_grouped",
    "test_is_first_distinct_expr_lazy_w_nulls",
    "test_is_into_dataframe",
    "test_is_into_lazyframe",
    "test_is_into_series",
    "test_is_last_distinct_expr_all",
    "test_is_last_distinct_expr_lazy",
    "test_is_last_distinct_expr_lazy_grouped",
    "test_is_last_distinct_expr_lazy_grouped_nulls",
    "test_is_sorted_invalid",
    "test_is_unique",
    "test_is_unique_expr_grouped",
    "test_is_unique_with_nulls",
    "test_issue_3474_expr_decimal",
    "test_issue_3474_series_decimal",
    "test_item_value_error",
    "test_join_duplicate_column_names",
    "test_join_on_null_values",
    "test_join_on_null_values_single_key",
    "test_join_on_strings",
    "test_joinasof_by",
    "test_joinasof_numeric",
    "test_joinasof_suffix",
    "test_joinasof_time",
    "test_kurtosis_expr",
    "test_kurtosis_series",
    "test_lazy_cum_count_grouped",
    "test_lazy_cum_max_grouped",
    "test_lazy_cum_max_ordered_by_nulls",
    "test_lazy_cum_max_ungrouped",
    "test_lazy_cum_max_ungrouped_ordered_by_nulls",
    "test_lazy_cum_min_grouped",
    "test_lazy_cum_min_ordered_by_nulls",
    "test_lazy_cum_min_ungrouped",
    "test_lazy_cum_min_ungrouped_ordered_by_nulls",
    "test_lazy_cum_prod_grouped",
    "test_lazy_cum_sum_grouped",
    "test_lazy_cum_sum_ordered_by_nulls",
    "test_lazy_cum_sum_ungrouped",
    "test_lazy_cum_sum_ungrouped_ordered_by_nulls",
    "test_lazy_rank_expr",
    "test_lazy_rank_expr_desc",
    "test_lazy_spark_like_requires_session",
    "test_lazy_to_default",
    "test_left_join",
    "test_left_join_multiple_column",
    "test_left_join_overlapping_column",
    "test_len_expr",
    "test_len_over_2369",
    "test_len_series",
    "test_list_like",
    "test_log_expr",
    "test_log_series",
    "test_logic_operators_expr_kleene",
    "test_map_batches_exception",
    "test_map_batches_expr_numpy_scalar",
    "test_mapping_key_not_in_expr",
    "test_mapping_key_not_in_series",
    "test_max_expr",
    "test_max_series",
    "test_mean_expr",
    "test_mean_series",
    "test_median_expr",
    "test_median_expr_raises_on_str",
    "test_median_series",
    "test_median_series_raises_on_str",
    "test_metadata_checks",
    "test_metadata_checks_with_flags",
    "test_min_expr",
    "test_min_series",
    "test_mode_different_lengths",
    "test_mode_different_lengths_keep_all",
    "test_mode_expr_keep_all_lazy",
    "test_mode_expr_keep_any",
    "test_mode_group_by_multimodal",
    "test_mode_group_by_multiple_cols",
    "test_mode_group_by_unimodal",
    "test_mode_series",
    "test_mode_series_keep_all",
    "test_mode_series_keep_any",
    "test_mode_single_expr",
    "test_mode_single_expr_keep_all",
    "test_mutability",
    "test_n_unique_over",
    "test_namespace_from_native_object",
    "test_nan",
    "test_nan_non_float",
    "test_nan_non_float_series",
    "test_nan_series",
    "test_native_namespace_frame",
    "test_native_namespace_series",
    "test_nested_structures",
    "test_new_series",
    "test_not_implemented",
    "test_otherwise_numpy_array",
    "test_over_anonymous_cumulative",
    "test_over_anonymous_reduction",
    "test_over_cum_reverse",
    "test_over_cumcount",
    "test_over_cummax",
    "test_over_cummin",
    "test_over_cumprod",
    "test_over_cumsum",
    "test_over_diff",
    "test_over_ewm_mean",
    "test_over_multiple",
    "test_over_pushdown",
    "test_over_quantile",
    "test_over_shift",
    "test_over_single",
    "test_over_std_var",
    "test_over_when_then_aggregation_partition_by",
    "test_over_with_nulls_in_partition",
    "test_over_without_partition_by",
    "test_per_group_broadcasting",
    "test_pivot",
    "test_pivot_names_out",
    "test_pivot_no_agg",
    "test_pivot_no_index",
    "test_pivot_sort_columns",
    "test_plugin",
    "test_quantile_expr",
    "test_quantile_expr_group_by",
    "test_quantile_series",
    "test_rank_expr",
    "test_rank_expr_in_over_context",
    "test_rank_expr_in_over_desc",
    "test_rank_series",
    "test_rank_with_order_by",
    "test_rank_with_order_by_and_partition_by",
    "test_replace_strict_expr_basic",
    "test_replace_strict_expr_with_default",
    "test_replace_strict_non_full",
    "test_replace_strict_series_basic",
    "test_replace_strict_series_with_default",
    "test_replace_strict_with_default_and_nulls",
    "test_replace_strict_with_default_mapping",
    "test_replace_strict_with_expressified_default",
    "test_replace_strict_with_series_default",
    "test_rolling_mean_expr",
    "test_rolling_mean_expr_lazy_grouped",
    "test_rolling_mean_expr_lazy_ungrouped",
    "test_rolling_mean_series",
    "test_rolling_std_expr",
    "test_rolling_std_expr_lazy_grouped",
    "test_rolling_std_expr_lazy_ungrouped",
    "test_rolling_std_series",
    "test_rolling_sum_expr",
    "test_rolling_sum_expr_lazy_grouped",
    "test_rolling_sum_expr_lazy_ungrouped",
    "test_rolling_sum_series",
    "test_rolling_var_expr",
    "test_rolling_var_expr_lazy_grouped",
    "test_rolling_var_expr_lazy_ungrouped",
    "test_rolling_var_series",
    "test_sample_default_single_row",
    "test_sample_fraction",
    "test_sample_n",
    "test_sample_with_seed",
    "test_scan_csv",
    "test_scan_parquet",
    "test_scatter",
    "test_scatter_2862",
    "test_scrambled_groups_over",
    "test_self_equal",
    "test_semi_join",
    "test_series_floordiv_by_zero",
    "test_series_rfloordiv_by_zero",
    "test_series_rtruediv_by_zero",
    "test_series_to_polars",
    "test_series_truediv_by_zero",
    "test_shift_cum_sum",
    "test_shift_lazy",
    "test_shift_lazy_grouped",
    "test_sink_parquet",
    "test_skew_expr",
    "test_skew_series",
    "test_sort_expr_args",
    "test_sort_series_args",
    "test_split_list_get",
    "test_sqrt_expr",
    "test_sqrt_series",
    "test_struct",
    "test_struct_mixed_series_and_exprs",
    "test_struct_named_exprs",
    "test_struct_named_with_series",
    "test_struct_positional_and_named",
    "test_struct_positional_exprs",
    "test_struct_with_expressions",
    "test_struct_with_literals",
    "test_struct_with_schema",
    "test_struct_with_series",
    "test_suffix",
    "test_sum_expr",
    "test_sum_series",
    "test_timestamp_datetimes",
    "test_timestamp_datetimes_tz_aware",
    "test_to_arrow",
    "test_to_arrow_with_nulls",
    "test_to_dummies",
    "test_to_dummies_drop_first",
    "test_to_dummies_drop_first_na",
    "test_to_native",
    "test_to_numpy",
    "test_to_numpy_tz_aware",
    "test_top_k",
    "test_top_k_by_multiple",
    "test_unary",
    "test_unary_one_element",
    "test_unary_one_element_series",
    "test_unary_series",
    "test_unary_two_elements",
    "test_unary_two_elements_series",
    "test_unique_expr",
    "test_unique_first_last",
    "test_unique_first_last_no_subset",
    "test_unique_series",
    "test_unpivot",
    "test_unpivot_default_var_value_names",
    "test_unpivot_mixed_types",
    "test_unpivot_var_value_names",
    "test_value_counts",
    "test_value_numpy_array",
    "test_with_columns",
    "test_with_columns_dtypes_single_row",
    "test_with_row_index_lazy",
    "test_with_row_index_lazy_meaner_examples",
    "test_write_csv",
    "test_write_parquet",
]
# --- END TESTS_THAT_NEED_FIX ---
# fmt: on

BASE_COMMAND = [
    "uv",
    "run",
    "pytest",
    "tests",
    "-p",
    "narwhals_dict.testing",
    "--use-external-constructor",
]

FAILED_PATTERN = re.compile(r"^(?:FAILED|ERROR) tests/.*::(\w+)", re.MULTILINE)


def run_tests(extra_args: list[str]) -> int:
    command = [*BASE_COMMAND, *extra_args]
    if TESTS_THAT_NEED_FIX:
        command.extend(["-k", f"not ({' or '.join(TESTS_THAT_NEED_FIX)})"])
    return subprocess.run(command, check=False, cwd=REPO_ROOT).returncode  # noqa: S603


def update_known_failures() -> int:
    command = [*BASE_COMMAND, "-p", "no:randomly", "--tb=no", "-q"]
    result = subprocess.run(  # noqa: S603
        command, check=False, cwd=REPO_ROOT, capture_output=True, text=True
    )
    failures = sorted(set(FAILED_PATTERN.findall(result.stdout)))

    this_file = Path(__file__)
    content = this_file.read_text(encoding="utf-8")
    lines = ",\n".join(f'    "{name}"' for name in failures)
    replacement = (
        "# --- BEGIN TESTS_THAT_NEED_FIX (auto-generated, see --update) ---\n"
        f"TESTS_THAT_NEED_FIX: list[str] = [\n{lines},\n]\n"
        if failures
        else "# --- BEGIN TESTS_THAT_NEED_FIX (auto-generated, see --update) ---\n"
        "TESTS_THAT_NEED_FIX: list[str] = []\n"
    )
    content = re.sub(
        r"# --- BEGIN TESTS_THAT_NEED_FIX \(auto-generated, see --update\) ---\n.*?(?=# --- END TESTS_THAT_NEED_FIX ---)",
        replacement,
        content,
        flags=re.DOTALL,
    )
    this_file.write_text(content, encoding="utf-8")
    sys.stdout.write(f"Updated TESTS_THAT_NEED_FIX with {len(failures)} entries.\n")
    return 0


if __name__ == "__main__":
    args = sys.argv[1:]
    if "--update" in args:
        raise SystemExit(update_known_failures())
    raise SystemExit(run_tests(args))
