from __future__ import annotations

from typing import TYPE_CHECKING, Any, ClassVar, Protocol, TypeVar

from narwhals._plan.compliant.typing import Native

if TYPE_CHECKING:
    from typing_extensions import TypeAlias

    from narwhals._plan.compliant.lazyframe import CompliantLazyFrame
    from narwhals._plan.compliant.typing import DataFrameAny as CompliantDataFrameAny
    from narwhals._plan.plans import logical as lp, resolved as rp
    from narwhals._plan.plans.resolved import ResolvedPlan
    from narwhals._utils import Version
    from narwhals.typing import EagerAllowed

R_co = TypeVar("R_co", covariant=True)
Incomplete: TypeAlias = Any


class LogicalVisitor(Protocol[R_co]):
    """Generic `LogicalPlan` visitor protocol.

    Defines the method name of each node.
    """

    def collect(self, plan: lp.Collect, /) -> R_co: ...
    def concat_horizontal(self, plan: lp.HConcat, /) -> R_co: ...
    def concat_vertical(self, plan: lp.VConcat, /) -> R_co: ...
    def explode(self, plan: lp.MapFunction[lp.Explode], /) -> R_co: ...
    def filter(self, plan: lp.Filter, /) -> R_co: ...
    def group_by(self, plan: lp.GroupBy, /) -> R_co: ...
    def join(self, plan: lp.Join, /) -> R_co: ...
    def join_asof(self, plan: lp.JoinAsof, /) -> R_co: ...
    def map_function(self, plan: lp.MapFunction[lp.LpFunctionT_co], /) -> R_co: ...
    def pivot(self, plan: lp.Pivot, /) -> R_co: ...
    def rename(self, plan: lp.MapFunction[lp.Rename], /) -> R_co: ...
    def scan_csv(self, plan: lp.ScanCsv, /) -> R_co: ...
    def scan_dataframe(self, plan: lp.ScanDataFrame, /) -> R_co: ...
    def scan_lazyframe(self, plan: lp.ScanLazyFrame[Native], /) -> R_co: ...
    def scan_parquet(self, plan: lp.ScanParquet, /) -> R_co: ...
    def select(self, plan: lp.Select, /) -> R_co: ...
    def select_names(self, plan: lp.SelectNames, /) -> R_co: ...
    def sink_parquet(self, plan: lp.SinkParquet, /) -> R_co: ...
    def slice(self, plan: lp.Slice, /) -> R_co: ...
    def sort(self, plan: lp.Sort, /) -> R_co: ...
    def unique(self, plan: lp.Unique, /) -> R_co: ...
    def unique_by(self, plan: lp.UniqueBy, /) -> R_co: ...
    def unnest(self, plan: lp.MapFunction[lp.Unnest], /) -> R_co: ...
    def unpivot(self, plan: lp.MapFunction[lp.Unpivot], /) -> R_co: ...
    def with_columns(self, plan: lp.WithColumns, /) -> R_co: ...
    def with_row_index(self, plan: lp.MapFunction[lp.RowIndex], /) -> R_co: ...
    def with_row_index_by(self, plan: lp.MapFunction[lp.RowIndexBy], /) -> R_co: ...


class LogicalToResolved(LogicalVisitor["ResolvedPlan"], Protocol):
    """`LogicalPlan` -> `ResolvedPlan` visitor."""

    def map_function(self, plan: lp.MapFunction[lp.LpFunctionT_co], /) -> ResolvedPlan:
        return plan.function.resolve(self, plan)


class ResolvedToCompliant(Protocol[Native]):
    """`[Native]`.

    `ResolvedPlan` -> `CompliantLazyFrame[Native]`.
    """

    __slots__ = ()
    version: ClassVar[Version]

    @classmethod
    def collect(
        cls, plan: rp.Collect, /, backend: EagerAllowed | None = None
    ) -> CompliantDataFrameAny: ...
    @classmethod
    def sink_parquet(cls, plan: rp.SinkParquet, /) -> None: ...
    def map_function(
        self, plan: rp.MapFunction[rp.RpFunctionT_co], /
    ) -> CompliantLazyFrame[Native]:
        return plan.function.evaluate(self, plan)

    def concat_horizontal(self, plan: rp.HConcat, /) -> CompliantLazyFrame[Native]: ...
    def concat_vertical(self, plan: rp.VConcat, /) -> CompliantLazyFrame[Native]: ...
    def explode(
        self, plan: rp.MapFunction[rp.Explode], /
    ) -> CompliantLazyFrame[Native]: ...
    def filter(self, plan: rp.Filter, /) -> CompliantLazyFrame[Native]: ...
    def group_by(self, plan: rp.GroupBy, /) -> CompliantLazyFrame[Native]: ...
    def group_by_names(self, plan: rp.GroupByNames, /) -> CompliantLazyFrame[Native]: ...
    def join(self, plan: rp.Join, /) -> CompliantLazyFrame[Native]: ...
    def join_asof(self, plan: rp.JoinAsof, /) -> CompliantLazyFrame[Native]: ...
    # TODO @dangotbanned: `pivot` (low priority)
    def rename(
        self, plan: rp.MapFunction[rp.Rename], /
    ) -> CompliantLazyFrame[Native]: ...
    # TODO @dangotbanned: `lp.Scan*[Native]` -> `rp.Scan*[Native]` -> `CompliantLazyFrame[Native]`
    def scan_csv(self, plan: rp.ScanCsv, /) -> CompliantLazyFrame[Native]: ...
    def scan_dataframe(self, plan: rp.ScanDataFrame, /) -> CompliantLazyFrame[Native]: ...
    def scan_lazyframe(
        self, plan: rp.ScanLazyFrame[Native], /
    ) -> CompliantLazyFrame[Native]: ...
    def scan_parquet(self, plan: rp.ScanParquet, /) -> CompliantLazyFrame[Native]: ...
    def select(self, plan: rp.Select, /) -> CompliantLazyFrame[Native]: ...
    def select_names(self, plan: rp.SelectNames, /) -> CompliantLazyFrame[Native]: ...
    def slice(self, plan: rp.Slice, /) -> CompliantLazyFrame[Native]: ...
    def sort(self, plan: rp.Sort, /) -> CompliantLazyFrame[Native]: ...
    def unique(self, plan: rp.Unique, /) -> CompliantLazyFrame[Native]: ...
    def unique_by(self, plan: rp.UniqueBy, /) -> CompliantLazyFrame[Native]: ...
    def unnest(
        self, plan: rp.MapFunction[rp.Unnest], /
    ) -> CompliantLazyFrame[Native]: ...
    def unpivot(
        self, plan: rp.MapFunction[rp.Unpivot], /
    ) -> CompliantLazyFrame[Native]: ...
    def with_columns(self, plan: rp.WithColumns, /) -> CompliantLazyFrame[Native]: ...
    def with_row_index(
        self, plan: rp.MapFunction[rp.RowIndex], /
    ) -> CompliantLazyFrame[Native]: ...
    def with_row_index_by(
        self, plan: rp.MapFunction[rp.RowIndexBy], /
    ) -> CompliantLazyFrame[Native]: ...


ResolvedToCompliantAny: TypeAlias = ResolvedToCompliant[Any]
