name: Publish Docs

on:
  push:
    branches:
      - main
env:
  cache_id: ""
  UV_SYSTEM_PYTHON: 1
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/checkout@v6
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - name: Install dependencies
        run: uv pip install -e ".[dask,ibis]" --group docs
      - name: Run hooks manually
        run: |
          python utils/generate_backend_completeness.py
          python utils/generate_zen_content.py
      - run: zensical build --clean
      - uses: actions/upload-pages-artifact@v4
        with:
          path: site
      - uses: actions/deploy-pages@v4
        id: deployment
