name: PyTest Ibis constructor

on:
  pull_request:
    paths:
      - src/narwhals/_expression_parsing.py
      - src/narwhals/_ibis/**
      - src/narwhals/_sql/**      
      - tests/**
      - .github/workflows/pytest-ibis.yml
      - pyproject.toml
      - uv.lock
  workflow_call:

env:
  PY_COLORS: 1
  PYTEST_ADDOPTS: "--numprocesses=logical"
  COVERAGE_PROCESS_START: pyproject.toml
  UV_LOCKED: 1
  UV_NO_DEV: 1

permissions:
  contents: read

jobs:
  pytest-ibis-constructor:
    if: github.head_ref != 'bump-version'
    strategy:
      matrix:
        python-version: ["3.13"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: "true"
          cache-suffix: ibis-${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"
      - name: Run pytest
        run: make run-ci DEPS="--group core-tests --extra ibis --extra pandas" CMD="pytest tests --nw-backends=ibis"
