name: PyTest Modin constructor

on:
  pull_request:
  workflow_call:

env:
  PY_COLORS: 1
  PYTEST_ADDOPTS: "--numprocesses=logical"
  UV_LOCKED: 1
  UV_NO_DEV: 1

permissions:
  contents: read

jobs:
  pytest-modin-constructor:
    if: github.head_ref != 'bump-version'
    strategy:
      matrix:
        python-version: ["3.13"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: "true"
          cache-suffix: modin-${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"
      - name: Show dependencies
        run: uv export --no-annotate --no-hashes --group core-tests --extra modin
      - name: Run pytest
        run: |
          uv run --group core-tests --extra modin \
          pytest tests --constructors="modin[pyarrow]"
