name: PyTest Ibis constructor

on:
  pull_request:

env:
  PY_COLORS: 1
  PYTEST_ADDOPTS: "--numprocesses=logical"
  COVERAGE_PROCESS_START: pyproject.toml
  UV_SYSTEM_PYTHON: 1

permissions:
  contents: read

jobs:

  pytest-ibis-constructor:
    strategy:
      matrix:
        python-version: ["3.13"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: "true"
          cache-suffix: ibis-${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"
      - name: install-reqs
        run: uv pip install -e . --group core-tests
      - name: install ibis
        run: |
          # Temporary pin until it's fixed upstream
          uv pip install "sqlglot<28.6"
          uv pip install -e ".[ibis]"
      - name: show-deps
        run: uv pip freeze
      - name: Run pytest
        run: pytest tests --nw-backends ibis
