name: Random Versions

on:
  pull_request:

env:
  PY_COLORS: 1
  PYTEST_ADDOPTS: "--numprocesses=logical"
  UV_LOCKED: 1
  UV_NO_DEV: 1
  UV_PRERELEASE: "allow"

permissions:
  contents: read

jobs:
  tox:
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: "true"
          cache-suffix: pytest-random-ci-${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"
      - name: Generate random versions
        run: uv run --no-project python utils/generate_random_versions.py
      - name: Show dependencies
        run: uv pip compile random-requirements.txt --group tests
      - name: Run pytest with random versions
        run: |
          uv run --group tests --with-requirements random-requirements.txt \
          pytest tests --cov=src --cov=tests --cov-fail-under=75 \
          --constructors="pandas,pyarrow,polars[eager],polars[lazy]"
