name: Random Versions

on:
  pull_request:

env:
  PY_COLORS: 1
  PYTEST_ADDOPTS: "--numprocesses=logical"
  COVERAGE_PROCESS_START: pyproject.toml

permissions:
  contents: read

jobs:
  tox:
    strategy:
      matrix:
        python-version: ["3.9"]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: "true"
          cache-suffix: pytest-random-ci-${{ matrix.python-version }}
          cache-dependency-glob: "pyproject.toml"
      - name: generate-random-versions
        run: python utils/generate_random_versions.py
      - name: install-random-versions
        run: uv pip install -r random-requirements.txt --system
      - name: install-narwhals
        run: uv pip install -e . --group tests --system
      - name: show versions
        run: uv pip freeze
      - name: Run pytest
        run: |
            coverage run -m pytest tests --nw-backends=pandas,pyarrow,polars[eager],polars[lazy]
            coverage combine
            coverage report --fail-under=75
